name: Docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        run: |
          cd docs
          export USERID=$(id -u) && export GROUPID=$(id -g) && docker compose run --rm mdbook build
          cd ..
      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: ${{ github.event_name != 'pull_request' }}
        id: pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: ./docs/book
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        